import { Component, OnInit, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { DatePipe, NgFor, NgIf } from '@angular/common';
import { RuntimeConfigService } from '../core/runtime-config.service';
import { Occurrence, dateKey, occurrenceFunction, occurrencesForDay, occurrenceTime, occurrenceTitle, statusPresentation } from '../core/presentation';
@Component({ standalone: true, imports: [NgFor, NgIf, DatePipe], template: `
<section><div class="page-heading calendar-heading"><div><p class="eyebrow">Agenda da equipe</p><h1>Calendário</h1><p class="muted">{{days[0] | date:'dd MMM'}} — {{days[6] | date:'dd MMM, y'}}</p></div><div class="calendar-actions"><button class="secondary-button" (click)="previous()" aria-label="Semana anterior">←</button><button class="secondary-button" (click)="today()">Hoje</button><button class="secondary-button" (click)="next()" aria-label="Próxima semana">→</button></div></div><p *ngIf="error" class="error">{{error}}</p><div class="week-calendar" *ngIf="!loading; else loading"><div class="day-column" *ngFor="let day of days"><header [class.today]="isToday(day)"><span>{{day | date:'EEE'}}</span><b>{{day | date:'dd'}}</b></header><div class="day-events"><button class="event-card" [class]="'event-card ' + status(item).tone" *ngFor="let item of byDay(day)" (click)="selected=item"><span>{{time(item)}}</span><b>{{title(item)}}</b><small>{{function(item)}}</small></button><p class="calendar-empty" *ngIf="byDay(day).length === 0">Sem ocorrências</p></div></div></div><ng-template #loading><div class="loading-block">Carregando agenda…</div></ng-template><div class="modal-backdrop" *ngIf="selected" (click)="selected = undefined"><article class="detail-modal" (click)="$event.stopPropagation()"><button class="close-button" (click)="selected = undefined" aria-label="Fechar">×</button><p class="eyebrow">Detalhes da ocorrência</p><h2>{{title(selected)}}</h2><span class="status" [class]="'status ' + status(selected).tone">{{status(selected).label}}</span><dl><div><dt>Data</dt><dd>{{selected.scheduledDate | date:'dd/MM/yyyy'}}</dd></div><div><dt>Horário</dt><dd>{{time(selected)}}</dd></div><div><dt>Função</dt><dd>{{function(selected)}}</dd></div></dl></article></div></section>` })
export class CalendarComponent implements OnInit { private readonly http = inject(HttpClient); private readonly config = inject(RuntimeConfigService); current = this.monday(new Date()); occurrences: Occurrence[] = []; selected?: Occurrence; error = ''; loading = false;
  get days(): Date[] { return Array.from({ length: 7 }, (_, index) => new Date(this.current.getFullYear(), this.current.getMonth(), this.current.getDate() + index)); }
  title = occurrenceTitle; time = occurrenceTime; function = occurrenceFunction; status = (item: Occurrence) => statusPresentation(item.status);
  ngOnInit(): void { this.load(); } previous(): void { this.move(-7); } next(): void { this.move(7); } today(): void { this.current = this.monday(new Date()); this.load(); }
  byDay(day: Date): Occurrence[] { return occurrencesForDay(this.occurrences, day); } isToday(day: Date): boolean { return dateKey(day) === dateKey(new Date()); }
  private move(amount: number): void { this.current = new Date(this.current.getFullYear(), this.current.getMonth(), this.current.getDate() + amount); this.load(); }
  private load(): void { this.loading = true; this.error = ''; const params = new HttpParams().set('from', dateKey(this.days[0])).set('to', dateKey(this.days[6])); this.http.get<Occurrence[]>(`${this.config.apiUrl}/task-occurrences/calendar`, { params }).subscribe({ next: value => { this.occurrences = value; this.loading = false; }, error: () => { this.error = 'Não foi possível carregar o calendário.'; this.loading = false; } }); }
  private monday(date: Date): Date { const d = new Date(date.getFullYear(), date.getMonth(), date.getDate()); d.setDate(d.getDate() - (d.getDay() + 6) % 7); return d; }
}