import { Component, OnInit, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http'; import { DatePipe, NgFor, NgIf } from '@angular/common';
import { RuntimeConfigService } from '../core/runtime-config.service';
@Component({ standalone: true, imports: [NgFor, NgIf, DatePipe], template: `<section><div class="title-row"><div><h1>Calendário</h1><p>Ocorrências confirmadas pela API.</p></div><div><button (click)="previous()">←</button><button (click)="today()">Hoje</button><button (click)="next()">→</button></div></div><p *ngIf="error" class="error">{{error}}</p><div class="calendar"><article *ngFor="let day of days"><h3>{{day | date:'EEE, dd/MM'}}</h3><p *ngIf="byDay(day).length === 0">Sem ocorrências</p><button class="occurrence" *ngFor="let occurrence of byDay(day)" (click)="selected=occurrence"><b>{{occurrence.scheduledTime || '—'}}</b> {{occurrence.task?.name || 'Tarefa'}}<small>{{occurrence.status}}</small></button></article></div><dialog [open]="selected"><div *ngIf="selected"><h2>{{selected.task?.name}}</h2><p>Status: {{selected.status}}</p><p>Data: {{selected.scheduledDate | date:'dd/MM/yyyy'}}</p><button (click)="selected=null">Fechar</button></div></dialog></section>` })
export class CalendarComponent implements OnInit { private readonly http = inject(HttpClient); private readonly config = inject(RuntimeConfigService); current = this.monday(new Date()); occurrences: any[] = []; selected: any; error = '';
 get days(): Date[] { return Array.from({length:7}, (_, i) => new Date(this.current.getFullYear(), this.current.getMonth(), this.current.getDate() + i)); }
 ngOnInit(): void { this.load(); } previous(): void { this.current.setDate(this.current.getDate()-7); this.load(); } next(): void { this.current.setDate(this.current.getDate()+7); this.load(); } today(): void { this.current=this.monday(new Date()); this.load(); }
 byDay(day: Date): any[] { const key=this.iso(day); return this.occurrences.filter(o => String(o.scheduledDate).slice(0,10)===key); }
 private load(): void { const params=new HttpParams().set('from',this.iso(this.days[0])).set('to',this.iso(this.days[6])); this.http.get<any[]>(`${this.config.apiUrl}/task-occurrences/calendar`, {params}).subscribe({next:v=>{this.occurrences=v;this.error='';},error:()=>this.error='Não foi possível carregar o calendário.'}); }
 private monday(date: Date): Date { const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()); d.setDate(d.getDate()-(d.getDay()+6)%7); return d; } private iso(d:Date):string { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
}
