import { Component, OnInit, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DatePipe, NgFor, NgIf } from '@angular/common';
import { RuntimeConfigService } from '../core/runtime-config.service';
import { DashboardSummary, Occurrence, occurrenceFunction, occurrenceTime, occurrenceTitle, statusPresentation } from '../core/presentation';
@Component({ standalone: true, imports: [DatePipe, NgFor, NgIf], template: `
<section><div class="page-heading"><div><p class="eyebrow">Visão geral</p><h1>Dashboard</h1><p class="muted">Acompanhe o que precisa de atenção hoje.</p></div></div><p *ngIf="error" class="error">{{error}}</p><div class="metric-grid" *ngIf="summary; else loading"><article class="metric-card" *ngFor="let total of totals"><span class="metric-icon">{{total.icon}}</span><div><strong>{{total.value}}</strong><span>{{total.label}}</span></div></article></div><ng-template #loading><div class="loading-block">Carregando indicadores…</div></ng-template><div class="dashboard-grid" *ngIf="summary"><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Hoje</p><h2>Ocorrências do dia</h2></div><span class="count">{{todayOccurrences.length}}</span></div><div *ngIf="todayOccurrences.length; else emptyToday" class="occurrence-list"><div class="occurrence-row" *ngFor="let item of todayOccurrences"><span class="time">{{time(item)}}</span><div><b>{{title(item)}}</b><small>{{function(item)}}</small></div><span class="status" [class]="'status ' + status(item).tone">{{status(item).label}}</span></div></div><ng-template #emptyToday><p class="empty-state">Nenhuma ocorrência prevista para hoje.</p></ng-template></article><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Agenda</p><h2>Próximas ocorrências</h2></div></div><div *ngIf="nextOccurrences.length; else emptyNext" class="occurrence-list"><div class="occurrence-row" *ngFor="let item of nextOccurrences"><span class="date-chip">{{item.scheduledDate | date:'dd'}}<small>{{item.scheduledDate | date:'MMM'}}</small></span><div><b>{{title(item)}}</b><small>{{time(item)}} · {{function(item)}}</small></div><span class="status" [class]="'status ' + status(item).tone">{{status(item).label}}</span></div></div><ng-template #emptyNext><p class="empty-state">Nenhuma ocorrência futura encontrada.</p></ng-template></article></div></section>` })
export class DashboardComponent implements OnInit { private readonly http = inject(HttpClient); private readonly config = inject(RuntimeConfigService); summary?: DashboardSummary; error = '';
  get totals() { const t = this.summary?.totals ?? {}; return [{ label: 'Pendentes', value: t.pending ?? 0, icon: '◷' }, { label: 'Em andamento', value: t.inProgress ?? 0, icon: '↻' }, { label: 'Concluídas', value: t.completed ?? 0, icon: '✓' }, { label: 'Falhas', value: t.failed ?? 0, icon: '!' }, { label: 'Atrasadas', value: t.overdue ?? 0, icon: '↗' }]; }
  get todayOccurrences(): Occurrence[] { return this.summary?.todayOccurrences ?? []; } get nextOccurrences(): Occurrence[] { return this.summary?.nextOccurrences ?? []; }
  title = occurrenceTitle; time = occurrenceTime; function = occurrenceFunction; status = (item: Occurrence) => statusPresentation(item.status);
  ngOnInit(): void { this.http.get<DashboardSummary>(`${this.config.apiUrl}/dashboard/summary`).subscribe({ next: summary => this.summary = summary, error: () => this.error = 'Não foi possível carregar o dashboard.' }); }
}