import { Component, OnInit, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http'; import { ActivatedRoute } from '@angular/router'; import { NgFor, NgIf } from '@angular/common';
import { RuntimeConfigService } from '../core/runtime-config.service'; import { RecordValue, displayValue } from '../core/presentation';
type ResourceRow = Record<string, RecordValue>; type ApiList = ResourceRow[] | { data?: ResourceRow[] };
@Component({ standalone: true, imports: [NgFor, NgIf], template: `<section><div class="page-heading"><div><p class="eyebrow">Consulta</p><h1>{{title}}</h1><p class="muted">Dados atualizados diretamente pela API.</p></div></div><div *ngIf="pending" class="notice"><h2>Disponível em breve</h2><p>Não existe endpoint documentado para esta tela. Nenhum dado simulado é exibido.</p></div><ng-container *ngIf="!pending"><div class="toolbar"><label class="search-field"><span>⌕</span><input #search (keyup.enter)="load(search.value)" placeholder="Pesquisar registros"></label><button class="primary-button" (click)="load(search.value)">Pesquisar</button></div><p *ngIf="error" class="error">{{error}}</p><div class="loading-block" *ngIf="loading">Carregando registros…</div><div class="table-wrap" *ngIf="!loading"><table *ngIf="rows.length; else empty"><thead><tr><th *ngFor="let key of columns">{{label(key)}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let key of columns">{{display(row[key])}}</td></tr></tbody></table><ng-template #empty><div class="empty-state large">Nenhum registro encontrado.</div></ng-template></div></ng-container></section>` })
export class ResourceListComponent implements OnInit { private readonly route = inject(ActivatedRoute); private readonly http = inject(HttpClient); private readonly config = inject(RuntimeConfigService); title = ''; endpoint = ''; pending = false; rows: ResourceRow[] = []; columns: string[] = []; error = ''; loading = false;
  ngOnInit(): void { const data = this.route.snapshot.data; this.title = data['title'] as string; this.endpoint = data['endpoint'] as string; this.pending = Boolean(data['pending']); if (!this.pending) this.load(); }
  load(search = ''): void { this.loading = true; this.error = ''; let params = new HttpParams().set('page', '1').set('limit', '20'); if (search) params = params.set('search', search); this.http.get<ApiList>(`${this.config.apiUrl}/${this.endpoint}`, { params }).subscribe({ next: response => { this.rows = Array.isArray(response) ? response : response.data ?? []; this.columns = this.rows.length ? Object.keys(this.rows[0]).filter(key => key !== 'passwordHash') : []; this.loading = false; }, error: () => { this.error = 'Não foi possível carregar os dados.'; this.loading = false; } }); }
  display = displayValue; label(key: string): string { return key.replace(/([A-Z])/g, ' $1').replace(/^./, value => value.toUpperCase()); }
}