import { Component, OnInit, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http'; import { ActivatedRoute } from '@angular/router'; import { NgFor, NgIf } from '@angular/common';
import { RuntimeConfigService } from '../core/runtime-config.service';
@Component({ standalone:true, imports:[NgFor,NgIf], template:`<section><h1>{{title}}</h1><div *ngIf="pending" class="notice"><h2>PendÃªncia de backend</h2><p>NÃ£o existe endpoint documentado para esta tela. Nenhum dado simulado Ã© exibido.</p></div><ng-container *ngIf="!pending"><div class="title-row"><input #search (keyup.enter)="load(search.value)" placeholder="Pesquisar"><button (click)="load(search.value)">Pesquisar</button></div><p *ngIf="error" class="error">{{error}}</p><p *ngIf="loading">Carregandoâ€¦</p><div class="table-wrap" *ngIf="!loading"><table><thead><tr><th *ngFor="let key of columns">{{key}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let key of columns">{{display(row[key])}}</td></tr><tr *ngIf="rows.length===0"><td [attr.colspan]="columns.length || 1">Nenhum registro encontrado.</td></tr></tbody></table></div></ng-container></section>`})
export class ResourceListComponent implements OnInit { private readonly route=inject(ActivatedRoute); private readonly http=inject(HttpClient); private readonly config=inject(RuntimeConfigService); title=''; endpoint=''; pending=false; rows:any[]=[]; columns:string[]=[]; error=''; loading=false;
 ngOnInit():void { const data=this.route.snapshot.data; this.title=data['title']; this.endpoint=data['endpoint']; this.pending=!!data['pending']; if(!this.pending)this.load(); }
 load(search=''):void { this.loading=true;this.error='';let params=new HttpParams().set('page','1').set('limit','20');if(search)params=params.set('search',search);this.http.get<any>(`${this.config.apiUrl}/${this.endpoint}`,{params}).subscribe({next:r=>{this.rows=Array.isArray(r)?r:(r.data||[]);this.columns=this.rows.length?Object.keys(this.rows[0]).filter(k=>!['passwordHash'].includes(k)):[];this.loading=false;},error:()=>{this.error='NÃ£o foi possÃ­vel carregar os dados.';this.loading=false;}}); }
 display(value:unknown):string { return typeof value==='object' ? JSON.stringify(value) : String(value ?? 'â€”'); }
}
